# Generated by Django 3.1.2 on 2020-12-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('sectors', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('contracts', models.CharField(max_length=50)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.applicant')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
            ],
        ),
    ]
