# Generated by Django 3.1.2 on 2020-12-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='matching_skills',
            field=models.IntegerField(default=0),
        ),
    ]
