# Generated by Django 3.1.2 on 2020-12-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_offer_matching_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.CharField(default='Provo', max_length=100),
        ),
    ]
