# Generated by Django 3.1.2 on 2020-12-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('listing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('contracts', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200)),
            ],
        ),
    ]
