# Generated by Django 3.1.2 on 2020-12-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='required_skills',
            field=models.ManyToManyField(to='listings.Skill'),
        ),
    ]
