# Generated by Django 3.1.2 on 2020-12-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='organization_id',
            field=models.IntegerField(default=0),
        ),
    ]
