# Generated by Django 3.1.2 on 2020-12-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='compensation',
            field=models.CharField(default='$1.00', max_length=20),
        ),
    ]
