# Generated by Django 3.1.2 on 2020-12-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20201209_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='company_website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
