# Generated by Django 3.1.2 on 2020-12-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_required_skills'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(to='listings.Skill'),
        ),
    ]
